import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import ProfilePic from '@/components/ProfilePic'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WebZim | Full Stack Web Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Navbar /> */}
     
      {children}
      </body>
    </html>
  )
}
